services:
  php:
    image: php:8.2-fpm
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - proxy-reverso

  apache:
    image: httpd:2.4
    container_name: apache
    restart: unless-stopped
    ports:
      - "8181:80"
    volumes:
      - ./html:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - php
    networks:
      - proxy-reverso
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - proxy-reverso

volumes:
  mariadb_data:

networks:
  proxy-reverso:
    external: true  